use_frameworks!

source 'https://github.com/EastWestBank/VLPodSpec.git'

target 'VLCheckDeposit_Example' do
  pod 'VLCheckDeposit', :path => '../'

  target 'VLCheckDeposit_Tests' do
    inherit! :search_paths

    
  end
end
